# Generated by Django 4.0.5 on 2022-06-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_stock_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not-Delivered', 'not-Delivered')], max_length=20, null=True),
        ),
    ]
