# Generated by Django 4.0.5 on 2022-06-07 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_payment_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('bill_num', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50, verbose_name='Custome Name')),
                ('total_sum', models.FloatField(default=2.0)),
            ],
        ),
        migrations.CreateModel(
            name='bill_product',
            fields=[
                ('bill_product_num', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, help_text='default is 1')),
                ('bill_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bill')),
                ('billprod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(to='app.bill_product'),
        ),
    ]
